# -*- perl -*-
use strict;
use warnings;
use tests::tests;
check_expected ([<<'EOF']);
(priority-queue) begin
Initialized the values
Finished 1 round of tests
Finished 2 rounds of tests
Finished 3 rounds of tests
Finished 4 rounds of tests
Finished 5 rounds of tests
Finished 6 rounds of tests
Finished 7 rounds of tests
Finished 8 rounds of tests
Finished 9 rounds of tests
Finished 10 rounds of tests
Finished 11 rounds of tests
Finished 12 rounds of tests
Finished 13 rounds of tests
Finished 14 rounds of tests
Finished 15 rounds of tests
Finished 16 rounds of tests
Finished 17 rounds of tests
Finished 18 rounds of tests
Finished 19 rounds of tests
Finished 20 rounds of tests
Finished 21 rounds of tests
Finished 22 rounds of tests
Finished 23 rounds of tests
Finished 24 rounds of tests
Finished 25 rounds of tests
Finished 26 rounds of tests
Finished 27 rounds of tests
Finished 28 rounds of tests
Finished 29 rounds of tests
Finished 30 rounds of tests
Finished 31 rounds of tests
Finished 32 rounds of tests
Finished 33 rounds of tests
Finished 34 rounds of tests
Finished 35 rounds of tests
Finished 36 rounds of tests
Finished 37 rounds of tests
Finished 38 rounds of tests
Finished 39 rounds of tests
Finished 40 rounds of tests
Finished 41 rounds of tests
Finished 42 rounds of tests
Finished 43 rounds of tests
Finished 44 rounds of tests
Finished 45 rounds of tests
Finished 46 rounds of tests
Finished 47 rounds of tests
Finished 48 rounds of tests
Finished 49 rounds of tests
Finished 50 rounds of tests
Finished 51 rounds of tests
Finished 52 rounds of tests
Finished 53 rounds of tests
Finished 54 rounds of tests
Finished 55 rounds of tests
Finished 56 rounds of tests
Finished 57 rounds of tests
Finished 58 rounds of tests
Finished 59 rounds of tests
Finished 60 rounds of tests
Finished 61 rounds of tests
Finished 62 rounds of tests
Finished 63 rounds of tests
Finished 64 rounds of tests
Finished 65 rounds of tests
Finished 66 rounds of tests
Finished 67 rounds of tests
Finished 68 rounds of tests
Finished 69 rounds of tests
Finished 70 rounds of tests
Finished 71 rounds of tests
Finished 72 rounds of tests
Finished 73 rounds of tests
Finished 74 rounds of tests
Finished 75 rounds of tests
Finished 76 rounds of tests
Finished 77 rounds of tests
Finished 78 rounds of tests
Finished 79 rounds of tests
Finished 80 rounds of tests
Finished 81 rounds of tests
Finished 82 rounds of tests
Finished 83 rounds of tests
Finished 84 rounds of tests
Finished 85 rounds of tests
Finished 86 rounds of tests
Finished 87 rounds of tests
Finished 88 rounds of tests
Finished 89 rounds of tests
Finished 90 rounds of tests
Finished 91 rounds of tests
Finished 92 rounds of tests
Finished 93 rounds of tests
Finished 94 rounds of tests
Finished 95 rounds of tests
Finished 96 rounds of tests
Finished 97 rounds of tests
Finished 98 rounds of tests
Finished 99 rounds of tests
Finished 100 rounds of tests
(priority-queue) end
EOF
pass;